version: '3.4'

services:

  node-aisp:
    image: node-aisp:latest
    container_name: node-aisp
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:7733/status"]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 1s
    extra_hosts:
      - "gw.3scale.banfico.com:${HOST_IP}"
      - "auth.3scale.banfico.com:${HOST_IP}"
    environment:
      PORT: 7733
      APP_NAME: node-aisp
      PLATFORM_API: https://gw.lyze.faas.orufin.io
      PLATFORM_APP_ID: 8a00828a762d0fbc0176349468ff001b
      PLATFORM_APP_ID_HEADER: x-app-id
      PLATFORM_APP_USER_HEADER: x-user-id
      AUTH_CLIENT_ID: pritishlyze
      AUTH_CLIENT_SECRET: Password01!
      AUTH_TOKEN_URI: https://auth.lyze.faas.orufin.io/auth/realms/faas/protocol/openid-connect/token


